apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: falcos.falco.org
spec:
  group: falco.org
  names:
    kind: Falco
    listKind: FalcoList
    plural: falcos
    singular: falco
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: falcoexporters.falco.org
spec:
  group: falco.org
  names:
    kind: FalcoExporter
    listKind: FalcoExporterList
    plural: falcoexporters
    singular: falcoexporter
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: falco-operator
subjects:
- kind: ServiceAccount
  name: falco-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: falco-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: falco-operator
  template:
    metadata:
      labels:
        name: falco-operator
    spec:
      serviceAccountName: falco-operator
      containers:
        - name: falco-operator
          # Replace this with the built image name
          image: docker.io/sysdiglabs/falco-operator:1.4.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "falco-operator"
