# permissions for end users to view falcos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falco-viewer-role
rules:
- apiGroups:
  - falco.org
  resources:
  - falcos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - falco.org
  resources:
  - falcos/status
  verbs:
  - get
