# permissions for end users to edit falcoexporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falcoexporter-editor-role
rules:
- apiGroups:
  - falco.org
  resources:
  - falcoexporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - falco.org
  resources:
  - falcoexporters/status
  verbs:
  - get
