# permissions for end users to edit falcos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falco-editor-role
rules:
- apiGroups:
  - falco.org
  resources:
  - falcos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - falco.org
  resources:
  - falcos/status
  verbs:
  - get
