apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: falcoexporters.falco.org
spec:
  group: falco.org
  names:
    kind: FalcoExporter
    listKind: FalcoExporterList
    plural: falcoexporters
    singular: falcoexporter
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
