apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: falcos.falco.org
spec:
  group: falco.org
  names:
    kind: Falco
    listKind: FalcoList
    plural: falcos
    singular: falco
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
