apiVersion: falco.org/v1
kind: Falco
metadata:
  name: falco-sample
spec:
  # Default values copied from <project_dir>/helm-charts/falco/values.yaml
  affinity: {}
  auditLog:
    dynamicBackend:
      enabled: false
      url: ""
    enabled: false
  containerd:
    enabled: true
    socket: /run/containerd/containerd.sock
  customRules: {}
  daemonset:
    env: {}
    podAnnotations: {}
    updateStrategy:
      type: RollingUpdate
  docker:
    enabled: true
    socket: /var/run/docker.sock
  ebpf:
    enabled: false
    settings:
      hostNetwork: true
  extraArgs: []
  extraInitContainers: []
  fakeEventGenerator:
    args:
    - run
    - --loop
    - ^syscall
    enabled: false
    replicas: 1
  falco:
    bufferedOutputs: false
    fileOutput:
      enabled: false
      filename: ./events.txt
      keepAlive: false
    grpc:
      certChain: /etc/falco/certs/server.crt
      enabled: true
      listenPort: 5060
      privateKey: /etc/falco/certs/server.key
      rootCerts: /etc/falco/certs/ca.crt
      threadiness: 0
      unixSocketPath: unix:///var/run/falco/falco.sock
    grpcOutput:
      enabled: true
    httpOutput:
      enabled: false
      url: http://some.url
    jsonIncludeOutputProperty: true
    jsonOutput: false
    logLevel: info
    logStderr: true
    logSyslog: true
    outputs:
      maxBurst: 1000
      rate: 1
    priority: debug
    programOutput:
      enabled: false
      keepAlive: false
      program: mail -s "Falco Notification" someone@example.com
    rulesFile:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/falco_rules.local.yaml
    - /etc/falco/k8s_audit_rules.yaml
    - /etc/falco/rules.d
    stdoutOutput:
      enabled: true
    syscallEventDrops:
      actions:
      - log
      - alert
      maxBurst: 10
      rate: 0.03333
    syslogOutput:
      enabled: true
    timeFormatISO8601: false
    webserver:
      enabled: true
      k8sAuditEndpoint: /k8s-audit
      listenPort: 8765
  image:
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: falcosecurity/falco
    tag: 0.25.0
  integrations:
    gcscc:
      enabled: false
      webhookAuthenticationToken: b27511f86e911f20b9e0f9c8104b4ec4
      webhookUrl: http://sysdig-gcscc-connector.default.svc.cluster.local:8080/events
    natsOutput:
      enabled: false
      natsUrl: nats://nats.nats-io.svc.cluster.local:4222
    pubsubOutput:
      credentialsData: ""
      enabled: false
      projectID: ""
      topic: ""
    snsOutput:
      aws_access_key_id: ""
      aws_default_region: ""
      aws_secret_access_key: ""
      enabled: false
      topic: ""
  nodeSelector: {}
  podSecurityPolicy:
    create: false
  priorityClassName: null
  proxy:
    httpProxy: null
    httpsProxy: null
    noProxy: null
  rbac:
    create: true
  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  scc:
    create: true
  serviceAccount:
    create: true
    name: null
  timezone: null
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master


